@HostAddress = http://localhost:5072


###

GET {{HostAddress}}/rentaloffice HTTP/1.1

###

GET {{HostAddress}}/rentaloffice/BMW HTTP/1.1

###

POST {{HostAddress}}/rentaloffice HTTP/1.1
Content-Type: application/json

{
  "name": "BMW"
}

###

PUT {{HostAddress}}/rentaloffice HTTP/1.1
Content-Type: application/json

{
  "name": "BMW"
}

###

DELETE {{HostAddress}}/rentaloffice/BMW HTTP/1.1
