@HostAddress = http://localhost:5072


###

GET {{HostAddress}}/rentaloffice HTTP/1.1

###

GET {{HostAddress}}/rentaloffice/BMW%20%ed%8c%90%ea%b5%90%ec%a0%90 HTTP/1.1

###

PUT {{HostAddress}}/rentaloffice HTTP/1.1
Content-Type: application/json

{
  "name": "BMW 판교점",
  "region": "경기도 오산시 부산동"
}

###

DELETE {{HostAddress}}/rentaloffice/BMW%20%ed%8c%90%ea%b5%90%ec%a0%90 HTTP/1.1
